apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260617-155112-l2wsexj74mn4-service
spec:
  selector:
    app: enterprise-system-20260617-155112-l2wsexj74mn4
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
